# Generated by Django 6.0.4 on 2026-04-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Community name"),
        ),
        migrations.AlterField(
            model_name="community",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=100,
                verbose_name="Visibility",
            ),
        ),
    ]
